In [1]:
import pandas as pd
data= {
    'Marks':[40,50,60,70,80]
}

In [3]:
df= pd.DataFrame(data)

In [4]:
df

   Marks
0     40
1     50
2     60
3     70
4     80

In [5]:
df_minmax=(df-df.min())/(df.max()-df.min())
print(df_minmax)

   Marks
0   0.00
1   0.25
2   0.50
3   0.75
4   1.00

In [1]:
import pandas as pd
df=pd.read_csv(r"11prog_3Salary_Data.csv")
df

    YearsExperience  Salary
0               1.1   39343
1               1.3   46205
2               1.5   37731
3               2.0   43525
4               2.2   39891
5               2.9   56642
6               3.0   60150
7               3.2   54445
8               3.2   64445
9               3.7   57189
10              3.9   63218
11              4.0   55794
12              4.0   56957
13              4.1   57081
14              4.5   61111
15              4.9   67938
16              5.1   66029
17              5.3   83088
18              5.9   81363
19              6.0   93940
20              6.8   91738
21              7.1   98273
22              7.9  101302
23              8.2  113812
24              8.7  109431
25              9.0  105582
26              9.5  116969
27              9.6  112635
28             10.3  122391
29             10.5  121872

In [2]:
from sklearn.preprocessing import StandardScaler

In [3]:
scaler=StandardScaler()
scaled_data=scaler.fit_transform(df)
scaled_df1=pd.DataFrame(scaled_data, columns=df.columns)
scaled_df1

    YearsExperience    Salary
0         -1.510053 -1.360113
1         -1.438373 -1.105527
2         -1.366693 -1.419919
3         -1.187494 -1.204957
4         -1.115814 -1.339781
5         -0.864935 -0.718307
6         -0.829096 -0.588158
7         -0.757416 -0.799817
8         -0.757416 -0.428810
9         -0.578216 -0.698013
10        -0.506537 -0.474333
11        -0.470697 -0.749769
12        -0.470697 -0.706620
13        -0.434857 -0.702020
14        -0.291498 -0.552504
15        -0.148138 -0.299217
16        -0.076458 -0.370043
17        -0.004779  0.262859
18         0.210261  0.198860
19         0.246100  0.665476
20         0.532819  0.583780
21         0.640339  0.826233
22         0.927058  0.938611
23         1.034577  1.402741
24         1.213777  1.240203
25         1.321296  1.097402
26         1.500496  1.519868
27         1.536336  1.359074
28         1.787215  1.721028
29         1.858894  1.701773

In [4]:
from sklearn.preprocessing import MinMaxScaler

In [5]:
scaler = MinMaxScaler()

In [6]:
scaled_data = scaler.fit_transform(df)

In [7]:
df_minmax = pd.DataFrame(scaled_data, columns=df.columns)
print(df_minmax)

    YearsExperience    Salary
0          0.000000  0.019041
1          0.021277  0.100094
2          0.042553  0.000000
3          0.095745  0.068438
4          0.117021  0.025514
5          0.191489  0.223376
6          0.202128  0.264812
7          0.223404  0.197425
8          0.223404  0.315545
9          0.276596  0.229837
10         0.297872  0.301051
11         0.308511  0.213359
12         0.308511  0.227097
13         0.319149  0.228561
14         0.361702  0.276163
15         0.404255  0.356804
16         0.425532  0.334255
17         0.446809  0.535755
18         0.510638  0.515379
19         0.521277  0.663938
20         0.606383  0.637928
21         0.638298  0.715119
22         0.723404  0.750898
23         0.755319  0.898665
24         0.808511  0.846917
25         0.840426  0.801453
26         0.893617  0.935956
27         0.904255  0.884763
28         0.978723  1.000000
29         1.000000  0.993870

In [8]:
from sklearn.preprocessing import StandardScaler

In [9]:
scaler = StandardScaler()

In [10]:
scaled_data = scaler.fit_transform(df)

In [11]:
df_zscore = pd.DataFrame(scaled_data, columns=df.columns)
print(df_zscore)

    YearsExperience    Salary
0         -1.510053 -1.360113
1         -1.438373 -1.105527
2         -1.366693 -1.419919
3         -1.187494 -1.204957
4         -1.115814 -1.339781
5         -0.864935 -0.718307
6         -0.829096 -0.588158
7         -0.757416 -0.799817
8         -0.757416 -0.428810
9         -0.578216 -0.698013
10        -0.506537 -0.474333
11        -0.470697 -0.749769
12        -0.470697 -0.706620
13        -0.434857 -0.702020
14        -0.291498 -0.552504
15        -0.148138 -0.299217
16        -0.076458 -0.370043
17        -0.004779  0.262859
18         0.210261  0.198860
19         0.246100  0.665476
20         0.532819  0.583780
21         0.640339  0.826233
22         0.927058  0.938611
23         1.034577  1.402741
24         1.213777  1.240203
25         1.321296  1.097402
26         1.500496  1.519868
27         1.536336  1.359074
28         1.787215  1.721028
29         1.858894  1.701773

In [12]:
print("\nMean after scaling:", scaled_data.mean())
print("\nStandard deviation after scaling:", scaled_data.std())

Mean after scaling: -2.2204460492503132e-17

Standard deviation after scaling: 1.0

In [13]:
print("Original Mean:", df.mean())
print("Original Std:", df.std())

Original Mean: YearsExperience        5.313333
Salary             76003.000000
dtype: float64
Original Std: YearsExperience        2.837888
Salary             27414.429785
dtype: float64