In [ ]:
#CATEGORICAL ENCODEING
#One Hot Encoding:Each categories into seperate columns
#Label Encoding:Categories into numericals labels
#sklearn is a library

In [5]:
import pandas as pd
df = pd.read_csv('10prog_4laptops.csv')
df.head

<bound method NDFrame.head of     Manufacturer       Model_Name   Category  Screen_size_inches  \
0          Apple      MacBook Pro  Ultrabook                13.3
1          Apple      Macbook Air  Ultrabook                13.3
2             HP           250 G6   Notebook                15.6
3          Apple      MacBook Pro  Ultrabook                15.4
4          Apple      MacBook Pro  Ultrabook                13.3
..           ...              ...        ...                 ...
972         Dell     Alienware 17     Gaming                17.3
973      Toshiba  Tecra A40-C-1DF   Notebook                14.0
974         Asus        Rog Strix     Gaming                17.3
975           HP      Probook 450   Notebook                15.6
976       Lenovo    ThinkPad T460   Notebook                14.0

                                 Screen                          CPU   RAM  \
0    IPS Panel Retina Display 2560x1600         Intel Core i5 2.3GHz   8GB
1                              1440x900         Intel Core i5 1.8GHz   8GB
2                     Full HD 1920x1080   Intel Core i5 7200U 2.5GHz   8GB
3    IPS Panel Retina Display 2880x1800         Intel Core i7 2.7GHz  16GB
4    IPS Panel Retina Display 2560x1600         Intel Core i5 3.1GHz   8GB
..                                  ...                          ...   ...
972                   Full HD 1920x1080  Intel Core i7 6700HQ 2.6GHz  32GB
973                   Full HD 1920x1080   Intel Core i5 6200U 2.3GHz   8GB
974                   Full HD 1920x1080  Intel Core i7 7700HQ 2.8GHz  16GB
975         IPS Panel Full HD 1920x1080  Intel Core i5 7200U 2.70GHz   8GB
976                            1366x768   Intel Core i5 6200U 2.3GHz   4GB

                  Storage                           GPU Operating_System  \
0               128GB SSD  Intel Iris Plus Graphics 640            macOS
1     128GB Flash Storage        Intel HD Graphics 6000            macOS
2               256GB SSD         Intel HD Graphics 620            No OS
3               512GB SSD            AMD Radeon Pro 455            macOS
4               256GB SSD  Intel Iris Plus Graphics 650            macOS
..                    ...                           ...              ...
972  256GB SSD +  1TB HDD       Nvidia GeForce GTX 1070          Windows
973             256GB SSD         Intel HD Graphics 520          Windows
974  256GB SSD +  1TB HDD       Nvidia GeForce GTX 1060          Windows
975  128GB SSD +  1TB HDD          Nvidia GeForce 930MX          Windows
976          508GB Hybrid         Intel HD Graphics 520          Windows

    Operating_System_Version  Weight_kg        Price
0                        NaN       1.37  11912523.48
1                        NaN       1.34   7993374.48
2                        NaN       1.86   5112900.00
3                        NaN       1.83  22563005.40
4                        NaN       1.37  16037611.20
..                       ...        ...          ...
972                       10       4.42  24897600.00
973                       10       1.95  10492560.00
974                       10       2.73  18227710.80
975                       10       2.04   8705268.00
976                        7       1.70   8909784.00

[977 rows x 13 columns]>

In [6]:
pd.get_dummies(df)

,Screen_size_inches,Weight_kg,Price,Manufacturer_Acer,Manufacturer_Apple,Manufacturer_Asus,Manufacturer_Chuwi,Manufacturer_Dell,Manufacturer_Fujitsu,Manufacturer_Google,...,Operating_System_Chrome OS,Operating_System_Linux,Operating_System_Mac OS,Operating_System_No OS,Operating_System_Windows,Operating_System_macOS,Operating_System_Version_10,Operating_System_Version_10 S,Operating_System_Version_7,Operating_System_Version_X
0,13.3,1.37,11912523.48,False,True,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
1,13.3,1.34,7993374.48,False,True,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
2,15.6,1.86,5112900.00,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
3,15.4,1.83,22563005.40,False,True,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
4,13.3,1.37,16037611.20,False,True,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
972,17.3,4.42,24897600.00,False,False,False,False,True,False,False,...,False,False,False,False,True,False,True,False,False,False
973,14.0,1.95,10492560.00,False,False,False,False,False,False,False,...,False,False,False,False,True,False,True,False,False,False
974,17.3,2.73,18227710.80,False,False,True,False,False,False,False,...,False,False,False,False,True,False,True,False,False,False
975,15.6,2.04,8705268.00,False,False,False,False,False,False,False,...,False,False,False,False,True,False,True,False,False,False
976,14.0,1.70,8909784.00,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,True,False

In [7]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder()
enc_data = enc.fit_transform(df[['Category']])
enc_data

<977x6 sparse matrix of type '<class 'numpy.float64'>'
	with 977 stored elements in Compressed Sparse Row format>

In [8]:
enc_data.toarray()
enc_df = pd.DataFrame(enc_data.toarray())
enc_df

       0    1    2    3    4    5
0    0.0  0.0  0.0  0.0  1.0  0.0
1    0.0  0.0  0.0  0.0  1.0  0.0
2    0.0  0.0  0.0  1.0  0.0  0.0
3    0.0  0.0  0.0  0.0  1.0  0.0
4    0.0  0.0  0.0  0.0  1.0  0.0
..   ...  ...  ...  ...  ...  ...
972  0.0  1.0  0.0  0.0  0.0  0.0
973  0.0  0.0  0.0  1.0  0.0  0.0
974  0.0  1.0  0.0  0.0  0.0  0.0
975  0.0  0.0  0.0  1.0  0.0  0.0
976  0.0  0.0  0.0  1.0  0.0  0.0

[977 rows x 6 columns]

In [9]:
enc_df = pd.DataFrame(enc_data.toarray(), columns = ['2 in 1 Convertible',
'Gaming', 'Netbook', 'Notebook', 'Ultrabook', 'Workstation'])
enc_df

     2 in 1 Convertible  Gaming  Netbook  Notebook  Ultrabook  Workstation
0                   0.0     0.0      0.0       0.0        1.0          0.0
1                   0.0     0.0      0.0       0.0        1.0          0.0
2                   0.0     0.0      0.0       1.0        0.0          0.0
3                   0.0     0.0      0.0       0.0        1.0          0.0
4                   0.0     0.0      0.0       0.0        1.0          0.0
..                  ...     ...      ...       ...        ...          ...
972                 0.0     1.0      0.0       0.0        0.0          0.0
973                 0.0     0.0      0.0       1.0        0.0          0.0
974                 0.0     1.0      0.0       0.0        0.0          0.0
975                 0.0     0.0      0.0       1.0        0.0          0.0
976                 0.0     0.0      0.0       1.0        0.0          0.0

[977 rows x 6 columns]

In [10]:
df1 = df.join(enc_df) 
df1

,Manufacturer,Model_Name,Category,Screen_size_inches,Screen,CPU,RAM,Storage,GPU,Operating_System,Operating_System_Version,Weight_kg,Price,2 in 1 Convertible,Gaming,Netbook,Notebook,Ultrabook,Workstation
0,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,NaN,1.37,11912523.48,0.0,0.0,0.0,0.0,1.0,0.0
1,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,NaN,1.34,7993374.48,0.0,0.0,0.0,0.0,1.0,0.0
2,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,NaN,1.86,5112900.00,0.0,0.0,0.0,1.0,0.0,0.0
3,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,NaN,1.83,22563005.40,0.0,0.0,0.0,0.0,1.0,0.0
4,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,NaN,1.37,16037611.20,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
972,Dell,Alienware 17,Gaming,17.3,Full HD 1920x1080,Intel Core i7 6700HQ 2.6GHz,32GB,256GB SSD + 1TB HDD,Nvidia GeForce GTX 1070,Windows,10,4.42,24897600.00,0.0,1.0,0.0,0.0,0.0,0.0
973,Toshiba,Tecra A40-C-1DF,Notebook,14.0,Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,8GB,256GB SSD,Intel HD Graphics 520,Windows,10,1.95,10492560.00,0.0,0.0,0.0,1.0,0.0,0.0
974,Asus,Rog Strix,Gaming,17.3,Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,16GB,256GB SSD + 1TB HDD,Nvidia GeForce GTX 1060,Windows,10,2.73,18227710.80,0.0,1.0,0.0,0.0,0.0,0.0
975,HP,Probook 450,Notebook,15.6,IPS Panel Full HD 1920x1080,Intel Core i5 7200U 2.70GHz,8GB,128GB SSD + 1TB HDD,Nvidia GeForce 930MX,Windows,10,2.04,8705268.00,0.0,0.0,0.0,1.0,0.0,0.0
976,Lenovo,ThinkPad T460,Notebook,14.0,1366x768,Intel Core i5 6200U 2.3GHz,4GB,508GB Hybrid,Intel HD Graphics 520,Windows,7,1.70,8909784.00,0.0,0.0,0.0,1.0,0.0,0.0

In [11]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [13]:
df['RAM'] = le.fit_transform(df['RAM'])
df
le.classes_

array([0, 1, 2, 3, 4, 5, 6, 7])

In [14]:
df['RAM']

0      7
1      7
2      7
3      1
4      7
      ..
972    4
973    7
974    1
975    7
976    5
Name: RAM, Length: 977, dtype: int64